# Generated by Django 6.0.1 on 2026-05-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
