# Generated by Django 6.0.1 on 2026-07-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
