# Generated by Django 6.0.1 on 2026-04-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_itemdetails_poster_contact_itemdetails_poster_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='type',
            field=models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], default='LOST', max_length=30),
        ),
    ]
