# Generated by Django 6.0.1 on 2026-04-29 05:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_itemdetails_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetails',
            name='created_at',
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='created_time',
            field=models.TimeField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
