# Generated by Django 6.0.1 on 2026-04-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_remove_itemdetails_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='created_time',
            field=models.TimeField(),
        ),
    ]
