# Generated by Django 6.0.1 on 2026-04-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_itemdetails_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Personal', 'Personal'), ('Accessories', 'Accessories'), ('Id', 'Id'), ('Electronics', 'Electronics'), ('Keys', 'Keys'), ('Valuables', 'Valuables')], default='ALL', max_length=30),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='location',
            field=models.CharField(choices=[('All', 'All'), ('Canteen', 'Canteen'), ('Gym', 'Gym'), ('Hs_Grounds', 'Highschool Grounds'), ('Basement', 'Basement'), ('Main_Building', 'Main Building'), ('Sao_Lobby', 'Sao Lobby'), ('Parking_Area', 'Parking Area')], default='ALL', max_length=30),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Claimed', 'Claimed'), ('Returned', 'Returned'), ('Archived', 'Archived')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='type',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], default='LOST', max_length=30),
        ),
    ]
