# Generated by Django 6.0.1 on 2026-04-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_alter_itemdetails_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='location',
            field=models.CharField(choices=[('All', 'All'), ('Canteen', 'Canteen'), ('Gym', 'Gym'), ('Highschool Grounds', 'Highschool Grounds'), ('Basement', 'Basement'), ('Main Building', 'Main Building'), ('Sao Lobby', 'Sao Lobby'), ('Parking Area', 'Parking Area')], default='All', max_length=30),
        ),
    ]
