# Generated by Django 6.0.4 on 2026-05-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_alter_itemdetails_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
