# Generated by Django 6.0.4 on 2026-05-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_itemdetails_ticket_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='declinedItems',
        ),
    ]
