# Generated by Django 6.0.1 on 2026-07-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_delete_declineditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='type',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Surrendered', 'Surrendered')], default='Lost', max_length=30),
        ),
    ]
