# Generated by Django 6.0.1 on 2026-07-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_alter_itemdetails_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='location',
            field=models.CharField(default='All', max_length=30),
        ),
    ]
