# Generated by Django 6.0.1 on 2026-07-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_alter_itemdetails_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdetails',
            old_name='poster_contact',
            new_name='email',
        ),
    ]
