# Generated by Django 6.0.1 on 2026-07-05 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_rename_poster_contact_itemdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
