# Generated by Django 6.0.1 on 2026-07-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_itemdetails_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
