# Generated by Django 6.0.1 on 2026-07-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_alter_itemdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='location',
            field=models.CharField(default='All', max_length=254),
        ),
    ]
