# Generated by Django 6.0.1 on 2026-07-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_alter_itemdetails_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='claimed_bonus_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='surrender_points_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
