# Generated by Django 6.0.1 on 2026-07-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_itemdetails_claimed_bonus_awarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='student_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
