# Generated by Django 6.0.1 on 2026-07-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_itemdetails_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='student_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
