# Generated by Django 6.0.1 on 2026-07-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_alter_itemdetails_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='decline_remark',
            field=models.TextField(blank=True, default=''),
        ),
    ]
