# Generated by Django 6.0.1 on 2026-07-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_itemdetails_decline_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Claimed', 'Claimed'), ('Returned', 'Returned'), ('Archived', 'Archived'), ('Declined', 'Declined')], default='Pending', max_length=30),
        ),
    ]
