# Generated by Django 6.0.1 on 2026-07-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_alter_itemdetails_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdetails',
            old_name='poster_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
