# Generated by Django 6.0.1 on 2026-07-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_rename_poster_name_itemdetails_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
