# Generated by Django 6.0.4 on 2026-05-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claimant_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='meeting_location',
            field=models.CharField(default='Student Affairs Office', max_length=100),
        ),
    ]
