# Generated by Django 6.0.1 on 2026-07-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0002_claim_claimant_email_claim_meeting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='meeting_time',
            field=models.CharField(blank=True, choices=[('9:00 AM - 10:00 AM', '9:00 AM - 10:00 AM'), ('10:00 AM - 11:00 AM', '10:00 AM - 11:00 AM'), ('11:00 AM - 12:00 PM', '11:00 AM - 12:00 PM'), ('1:00 PM - 2:00 PM', '1:00 PM - 2:00 PM'), ('2:00 PM - 3:00 PM', '2:00 PM - 3:00 PM')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
