# Generated by Django 6.0.1 on 2026-07-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardplayer',
            name='student_id',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaderboardplayer',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
