# Generated by Django 6.0.4 on 2026-07-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_leaderboardsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboardsettings',
            name='close_date',
        ),
        migrations.RemoveField(
            model_name='leaderboardsettings',
            name='open_date',
        ),
    ]
