# Generated by Django 6.0.4 on 2026-07-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_remove_leaderboardsettings_close_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardsettings',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardsettings',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
