# Generated by Django 6.0.1 on 2026-07-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_leaderboardsettings_close_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaderboardSettings',
        ),
    ]
