# Generated by Django 6.0.1 on 2026-07-12 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_leaderboardsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=30)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('total_players', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-archived_at'],
                'constraints': [models.UniqueConstraint(fields=('school_year', 'semester'), name='unique_leaderboard_history_period')],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardHistoryPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('rank', models.PositiveIntegerField()),
                ('total_points', models.IntegerField(default=0)),
                ('surrendered_items', models.PositiveIntegerField(default=0)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='gamification.leaderboardhistory')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='gamification.leaderboardplayer')),
            ],
            options={
                'ordering': ['rank'],
                'constraints': [models.UniqueConstraint(fields=('history', 'player'), name='unique_player_per_history')],
            },
        ),
    ]
