# Generated by Django 6.0.1 on 2026-07-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_leaderboardhistory_leaderboardhistoryplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardhistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardhistory',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
